name: AirSink
options:
  bundleIdPrefix: com.maslyankov
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true

targets:
  AirSink:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.maslyankov.airsink
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_LSUIElement: NO
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
